# __CLAUDE_CONFIG_PS_BLOCK_START__
# Claude Code PowerShell functions — generated by claude-config

# Secrets yukle
$_secretsPath = "$env:USERPROFILE\.claude\secrets\secrets.env"
if (Test-Path $_secretsPath) {
    Get-Content $_secretsPath | ForEach-Object {
        if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
            [Environment]::SetEnvironmentVariable($Matches[1].Trim(), $Matches[2].Trim(), 'Process')
        }
    }
}

# Claude binary
function _claude_bin {
    # Secrets henuz yuklenmediyse yukle
    if (-not $env:ANTHROPIC_API_KEY) {
        $s = "$env:USERPROFILE\.claude\secrets\secrets.env"
        if (Test-Path $s) {
            Get-Content $s | ForEach-Object {
                if ($_ -match '^\s*([^#][^=]+)=(.*)$') {
                    [Environment]::SetEnvironmentVariable($Matches[1].Trim(), $Matches[2].Trim(), 'Process')
                }
            }
        }
    }
    $bin = "$env:USERPROFILE\.local\bin\claude.exe"
    if (-not (Test-Path $bin)) { $bin = "claude" }
    & $bin @args
}

# claude → settings.json modeli | claude bypass → bypass modda ac
function claude {
    if ($args.Count -gt 0 -and $args[0] -eq "bypass") {
        $rest = @(); if ($args.Count -gt 1) { $rest = $args[1..($args.Count-1)] }
        _claude_bin --dangerously-skip-permissions @rest
        return
    }
    _claude_bin @args
}

# cl → fzf ile proje sec, claude ac
function cl {
    if ($args.Count -gt 0 -and $args[0] -eq "bypass") {
        $rest = $args[1..($args.Count-1)]
        cl_bypass @rest
        return
    }
    $projectsDir = "__PROJECTS_DIR__"
    if (-not (Get-Command fzf -ErrorAction SilentlyContinue)) {
        Write-Host "fzf bulunamadi. Kur: winget install junegunn.fzf"
        return
    }
    $items = @()
    Get-ChildItem -Path $projectsDir -Directory | ForEach-Object {
        $d = $_.FullName
        $hasClaude = (Test-Path "$d\.claude") -or (Test-Path "$d\CLAUDE.md") -or (Test-Path "$d\.claude-plugin")
        if (-not $hasClaude) { return }
        $name = $_.Name
        $tag = "-"
        if (Test-Path "$d\pubspec.yaml") { $tag = "Flutter" }
        elseif ((Test-Path "$d\Assets") -or (Test-Path "$d\ProjectSettings")) { $tag = "Unity" }
        elseif (Test-Path "$d\package.json") {
            if ((Test-Path "$d\app") -or (Select-String -Path "$d\package.json" -Pattern "next" -Quiet -ErrorAction SilentlyContinue)) { $tag = "Next.js" }
            else { $tag = "Node.js" }
        }
        elseif ((Test-Path "$d\pyproject.toml") -or (Test-Path "$d\requirements.txt")) { $tag = "Python" }
        elseif (Test-Path "$d\Cargo.toml") { $tag = "Rust" }
        elseif (Test-Path "$d\go.mod") { $tag = "Go" }
        $items += "{0,-30} [{1}]" -f $name, $tag
    }
    $selected = $items | fzf --height=60% --border=rounded --prompt="# Proje: " --header="Claude Projeleri  [Enter: ac, Esc: cik]" --cycle --nth=1
    if (-not $selected) { return }
    $dir = ($selected -replace '\s*\[.*$','').Trim()
    Set-Location "$projectsDir\$dir"
    _claude_bin @args
}

# cl_bypass → fzf ile proje sec, bypass modda ac
function cl_bypass {
    $projectsDir = "__PROJECTS_DIR__"
    if (-not (Get-Command fzf -ErrorAction SilentlyContinue)) {
        Write-Host "fzf bulunamadi. Kur: winget install junegunn.fzf"
        return
    }
    $items = @()
    Get-ChildItem -Path $projectsDir -Directory | ForEach-Object {
        $d = $_.FullName
        $hasClaude = (Test-Path "$d\.claude") -or (Test-Path "$d\CLAUDE.md") -or (Test-Path "$d\.claude-plugin")
        if (-not $hasClaude) { return }
        $name = $_.Name
        $tag = "-"
        if (Test-Path "$d\pubspec.yaml") { $tag = "Flutter" }
        elseif ((Test-Path "$d\Assets") -or (Test-Path "$d\ProjectSettings")) { $tag = "Unity" }
        elseif (Test-Path "$d\package.json") {
            if ((Test-Path "$d\app") -or (Select-String -Path "$d\package.json" -Pattern "next" -Quiet -ErrorAction SilentlyContinue)) { $tag = "Next.js" }
            else { $tag = "Node.js" }
        }
        elseif ((Test-Path "$d\pyproject.toml") -or (Test-Path "$d\requirements.txt")) { $tag = "Python" }
        elseif (Test-Path "$d\Cargo.toml") { $tag = "Rust" }
        elseif (Test-Path "$d\go.mod") { $tag = "Go" }
        $items += "{0,-30} [{1}]" -f $name, $tag
    }
    $selected = $items | fzf --height=60% --border=rounded --prompt="# Proje (bypass): " --header="Claude Projeleri - Bypass  [Enter: ac, Esc: cik]" --cycle --nth=1
    if (-not $selected) { return }
    $dir = ($selected -replace '\s*\[.*$','').Trim()
    Set-Location "$projectsDir\$dir"
    _claude_bin --dangerously-skip-permissions @args
}

# clhq → ClaudeHQ bypass
function clhq {
    Set-Location "__PROJECTS_DIR__\ClaudeHQ"
    _claude_bin --dangerously-skip-permissions @args
}

# plugin-update
function plugin-update { bash ~/Projects/claude-config/config/plugin-update.sh }

# __CLAUDE_CONFIG_PS_BLOCK_END__
