#!/usr/bin/env python3
"""
Generate runtime flat agent mirror files under ~/.claude/agents/<category>/<slug>.md.

Canonical sources:
- agents/<category>/<slug>/AGENT.md        -> scope, process, escalation metadata
- config/agent-registry.json               -> model, backend, fallback truth

The generated flat files are mirrors only. They should never become a hand-edited
source of truth again.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


def parse_inline_list(raw: str) -> list[str]:
    raw = raw.strip()
    if raw.startswith("[") and raw.endswith("]"):
        raw = raw[1:-1].strip()
    if not raw:
        return []
    items: list[str] = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        if len(part) >= 2 and part[0] == part[-1] and part[0] in ("'", '"'):
            part = part[1:-1]
        items.append(part)
    return items


def parse_scalar(raw: str) -> Any:
    raw = raw.strip()
    if raw == "":
        return ""
    if raw.startswith("[") and raw.endswith("]"):
        return parse_inline_list(raw)
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ("'", '"'):
        return raw[1:-1]
    if raw.lower() in {"true", "false"}:
        return raw.lower() == "true"
    if re.fullmatch(r"-?\d+", raw):
        return int(raw)
    return raw


def parse_frontmatter(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"^---\n([\s\S]*?)\n---\n?", text)
    if not match:
        return {}

    data: dict[str, Any] = {}
    current_map: str | None = None

    for line in match.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue

        indent = len(line) - len(line.lstrip(" "))
        stripped = line.strip()
        if ":" not in stripped:
            continue

        key, value = stripped.split(":", 1)
        key = key.strip()
        value = value.strip()

        if indent == 0:
            if value == "":
                data[key] = {}
                current_map = key
            else:
                data[key] = parse_scalar(value)
                current_map = None
            continue

        if current_map and isinstance(data.get(current_map), dict):
            data[current_map][key] = parse_scalar(value)

    return data


def inline_list(items: list[str]) -> str:
    return "[" + ", ".join(items) + "]"


def inline_value(value: Any) -> str:
    if isinstance(value, list):
        return inline_list([str(item) for item in value])
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def canonical_category(source_meta: dict[str, Any], registry_meta: dict[str, Any], agent_md: Path) -> str:
    for candidate in (
        registry_meta.get("category"),
        source_meta.get("category"),
        agent_md.parent.parent.name,
    ):
        if not candidate:
            continue
        value = str(candidate).strip()
        if "/" in value:
            value = value.split("/", 1)[0]
        if value:
            return value
    return "unknown"


def body_text(agent_id: str, name: str, source_rel: str) -> str:
    return "\n".join(
        [
            f"# {agent_id}: {name}",
            "",
            "> Generated mirror. Do not edit by hand.",
            "",
            "## Canonical Sources",
            f"- Source AGENT: `{source_rel}`",
            "- Source registry: `config/agent-registry.json`",
            "",
            "## Runtime Notes",
            "- Model, backend, fallback, and max-tool truth come from the source registry.",
            "- Scope, escalation, and process truth come from the source AGENT.md tree.",
            "- This file is regenerated by install/session sync.",
            "",
        ]
    )


def build_frontmatter(source_meta: dict[str, Any], registry_meta: dict[str, Any], source_rel: str) -> str:
    execution_backends = registry_meta.get("execution_backends", {})
    if not isinstance(execution_backends, dict):
        execution_backends = {}

    lines = [
        "---",
        f"id: {source_meta.get('id', registry_meta.get('id', ''))}",
        f"name: {source_meta.get('name', registry_meta.get('name', ''))}",
        f"category: {registry_meta.get('category', 'unknown')}",
        f"primary_model: {registry_meta.get('primary_model', source_meta.get('models', {}).get('mid', 'sonnet'))}",
    ]

    if registry_meta.get("primary_model_legacy"):
        lines.append(f"primary_model_legacy: {registry_meta['primary_model_legacy']}")
    if registry_meta.get("codex_model"):
        lines.append(f"codex_model: {registry_meta['codex_model']}")
    if registry_meta.get("execution_mode"):
        lines.append(f"execution_mode: {registry_meta['execution_mode']}")
    if execution_backends.get("primary"):
        lines.append(f"execution_backend: {execution_backends['primary']}")

    for key in ("fallbacks", "mcps", "capabilities", "related"):
        source_value = source_meta.get(key)
        registry_value = registry_meta.get(key)
        value = source_value if source_value not in (None, [], "") else registry_value
        if value not in (None, [], ""):
            lines.append(f"{key}: {inline_value(value)}")

    max_tool_calls = source_meta.get("max_tool_calls", registry_meta.get("max_tool_calls"))
    if max_tool_calls not in (None, ""):
        lines.append(f"max_tool_calls: {max_tool_calls}")

    for key in ("effort", "template", "status"):
        value = registry_meta.get(key, source_meta.get(key))
        if value not in (None, "", []):
            lines.append(f"{key}: {value}")

    lines.append(f"source_agent: {source_rel}")
    lines.append("---")
    return "\n".join(lines)


def cleanup_old_flat_files(runtime_agents_dir: Path) -> None:
    for path in runtime_agents_dir.glob("*/*.md"):
        if path.name == "README.md":
            continue
        path.unlink(missing_ok=True)
    for path in runtime_agents_dir.glob("*/*/*.md"):
        if path.name == "AGENT.md":
            continue
        if path.parent.name in {"knowledge", "memory"}:
            continue
        if path.stem == path.parent.name:
            path.unlink(missing_ok=True)


def generate(root: Path, runtime_agents_dir: Path) -> int:
    source_agents_dir = root / "agents"
    registry_path = root / "config" / "agent-registry.json"
    registry = json.loads(registry_path.read_text(encoding="utf-8"))
    registry_agents = registry.get("agents", {})

    runtime_agents_dir.mkdir(parents=True, exist_ok=True)
    cleanup_old_flat_files(runtime_agents_dir)

    generated = 0
    for agent_md in sorted(source_agents_dir.glob("*/*/AGENT.md")):
        source_meta = parse_frontmatter(agent_md)
        agent_id = str(source_meta.get("id", "")).strip()
        if not agent_id:
            continue

        registry_meta = dict(registry_agents.get(agent_id, {}))
        registry_meta.setdefault("id", agent_id)
        registry_meta.setdefault("name", source_meta.get("name", agent_md.parent.name))
        registry_meta.setdefault("category", source_meta.get("category", agent_md.parent.parent.name))

        category = canonical_category(source_meta, registry_meta, agent_md)
        registry_meta["category"] = category
        slug = agent_md.parent.name
        target = runtime_agents_dir / category / f"{slug}.md"
        target.parent.mkdir(parents=True, exist_ok=True)

        source_rel = str(agent_md.relative_to(root))
        content = build_frontmatter(source_meta, registry_meta, source_rel)
        content += "\n\n"
        content += body_text(agent_id, str(source_meta.get("name", registry_meta.get("name", slug))), source_rel)
        target.write_text(content, encoding="utf-8")
        generated += 1

    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate runtime flat agent mirrors.")
    parser.add_argument("--root", default=str(Path(__file__).resolve().parents[1]), help="claude-config root")
    parser.add_argument("--runtime-agents", default=str(Path.home() / ".claude" / "agents"), help="runtime ~/.claude/agents dir")
    parser.add_argument("--verbose", action="store_true", help="print generation summary")
    args = parser.parse_args()

    root = Path(args.root).expanduser().resolve()
    runtime_agents_dir = Path(args.runtime_agents).expanduser().resolve()
    generated = generate(root, runtime_agents_dir)
    if args.verbose:
        print(f"generated_runtime_agent_mirrors={generated}")


if __name__ == "__main__":
    main()
